jobs:
- job: tests
  trigger: pull_request
  branch: main
  targets:
    - fedora-stable
#    - fedora-rawhide
    - centos-stream-9-x86_64
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "main"
- job: tests
  trigger: pull_request
  branch: rhel-9-main
  targets:
    - centos-stream-9-x86_64
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "rhel-9-main"
- job: tests
  trigger: pull_request
  branch: fedora-main
  targets:
    - fedora-stable
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "fedora-main"
