jobs:
- job: tests
  trigger: pull_request
  branch: main
  targets:
    - fedora-stable
    - fedora-rawhide
    - centos-stream-10-x86_64
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "main"
- job: tests
  trigger: pull_request
  branch: rhel-9-main
  targets:
    centos-stream-9-x86_64:
        distros: [RHEL-9.5.0-Nightly]
  use_internal_tf: True
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "rhel-9-main"
